### PR TITLE
feat: add google sheets task templates

### PR DESCRIPTION
**Pull request by georgesafta**
Relates to boomerang-io/roadmap#278

Adding Google Sheets task templates.

#### Changelog

**New**

- added new task templates

**Changed**

N/A

**Removed**

N/A

#### Testing / Reviewing

N/A

### CODE REVIEW

**Comment by tlawrie** [comment]
Hi @georgesafta it all looks good. We just need to decide on the inputs.

**Review by tlawrie — APPROVED** [review]

**Comment by tlawrie** [comment]
@georgesafta as per comments on Worker, this is good to go!

**Comment by tlawrie** [comment]
@amhudson we will also need a default worker version change as part of this load but waiting on the new tag for the worker

**Comment by amhudson** [comment]
@tlawrie can you review the latest updates? If all good, I can merge

**Comment by tlawrie** [comment]
Hey @amhudson can we clear the image tags from these jsons? It should just pick up the default worker version.

**Pull request merged**
