### PR TITLE
loader documentation

### PR DESCRIPTION
**Pull request by amhudson**
Closes #

https://github.com/boomerang-io/flow.loader/issues/88

#### Changelog

**New**

- N/A

**Changed**

- Update README with documentation for loader update

**Removed**

- N/A

#### Testing / Reviewing

N/A

### CODE REVIEW

**Comment by tlawrie** [comment]
Hey @amhudson, some additional areas for thought

1. How to create a new vs update plus example snippets for each
2. Where to look for creating collections
3. A section on what indexes have been created (i.e. TTL on the flow_locks)

**Comment by amhudson** [comment]
yep, I need to circle back to this. Keep getting pulled into other things 😅

**Comment by amhudson** [comment]
@tlawrie I've updated the documentation on this branch. Please have a look over it and let me know of any gaps I may have.

**Comment by tlawrie** [comment]
HI @amhudson that looks great!

Only question I have is whether we could provide an example of a data migration?

**Comment by amhudson** [comment]
@tlawrie Not exactly sure what sort of data migration you mean. Is there a scenario you have in mind?

**Comment by tlawrie** [comment]
So typically we haven't had to do this much, but when we have had to alter the structure of an entity, we perform a migration of the existing data.

Is the an example that can show how to go from old to new for an existing collection?

**Comment by tlawrie** [comment]
And if you could also add instructions for running locally (I know you shared them in Slack)

**Comment by amhudson** [comment]
@tlawrie I've made the updates you requested. Please look over and let me know if there is anything else I need to update, clarify, etc.

**Review by tlawrie — APPROVED** [review]

**Pull request merged**
