### PR TITLE
Feat 368 v4migration java17

### PR DESCRIPTION
**Pull request by amhudson**
Closes #

https://github.com/boomerang-io/community/issues/367

#### Changelog

**New**

- Upgrade to support Java 17

**Changed**

- N/A

**Removed**

- N/A

#### Testing / Reviewing

Tested and verified locally.

### CODE REVIEW

**Comment by tlawrie** [comment]
Hey @amhudson - clarification around the collection prefix. Any particular reason why it has to be changed as to how its passed in?

In `[src/main/java/io/boomerang/migration/SpringContextBridge.java](https://github.com/boomerang-io/flow.loader/pull/97/files#diff-2a4537688a0af3be389531b4a8b51e370d04dbd576860fe6dbf854db2d77b2dc)` it pulls in from an App Property and we still use the mongo collection prefix with the Java 18 services.

**Comment by tlawrie** [comment]
Also doesn't -D just override what is in the application.properties anyway

**Comment by amhudson** [comment]
working late and couldn't get it to work last night. Updated today to read from app.prop

**Comment by tlawrie** [comment]
Thanks for adjusting. This is great work.

And Spring Boot 3.1.x! The other services haven't even been updated to Spring Boot 3.

**Comment by tlawrie** [comment]
Hey @amhudson in running some testing with a prefix, i think by moving the mongock properties to application.properties its not able to pick up the collections when they have a prefix.

We may have to move them back to the Config class that adds the prefix or some type of conditional property in the app props... I know there is the property reference / replacement `${ }` but not sure if there is conditional format.

```
mongock.enabled=true
mongock.runner-type=applicationrunner
mongock.lock-repository-name=sys_lock_flow
mongock.migration-repository-name=sys_changelog_flow
mongock.migration-scan-package=io.boomerang.migration.changesets
```

**Comment by amhudson** [comment]
With the mongock updates, the Config class was causing compilation issues as it was no longer recognized and the property configs have been moved to application.properties. 

I don't think there is a way for the application.properties values to be conditionally set and defining `mongock.lock-repository-name` and `mongock.migration-repository-name` with a property reference i.e. 

```
mongock.lock-repository-name=${flow.mongo.collection.prefix}sys_lock_flow
mongock.migration-repository-name=${flow.mongo.collection.prefix}sys_changelog_flow
```

won't result in the desired formatting. These properties may need to configured with the desired values via Helm.

**Comment by tlawrie** [comment]
I will get it a try and let you know how I go

**Pull request merged**
